/*
 * JS for findPartyScreen generated by Appery.io
 */

Appery.getProjectGUID = function() {
    return 'a616adf4-1952-491a-84e9-9c07b1a4d37f';
};

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "searchScreen",
    "location": "searchScreen.html"
}, {
    "name": "musicQueueScreen",
    "location": "musicQueueScreen.html"
}, {
    "name": "findPartyScreen",
    "location": "findPartyScreen.html"
}];

findPartyScreen_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'partyCollapsibleSet': 'findPartyScreen_partyCollapsibleSet',
        'newPartyCollapseBlock': 'findPartyScreen_newPartyCollapseBlock',
        'newPartyCollapseHeader': 'findPartyScreen_newPartyCollapseHeader',
        'newPartyCollapseBlockContent': 'findPartyScreen_newPartyCollapseBlockContent',
        'newPartyInsertName': 'findPartyScreen_newPartyInsertName',
        'newPartyInsert': 'findPartyScreen_newPartyInsert',
        'partyCollapseBlock': 'findPartyScreen_partyCollapseBlock',
        'partyCollapseBlockHeader': 'findPartyScreen_partyCollapseBlockHeader',
        'partyCollapseBlockContent': 'findPartyScreen_partyCollapseBlockContent',
        'partyInsertName': 'findPartyScreen_partyInsertName',
        'partyInsertName_nameInsertField': 'findPartyScreen_partyInsertName_nameInsertField'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        // Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=footer]").css("bottom", "-36px");
    }

    Appery.CurrentScreen = 'findPartyScreen';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var findPartyScreen_beforeshow = function() {
            Appery.CurrentScreen = "findPartyScreen";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var findPartyScreen_onLoad = function() {
            findPartyScreen_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            findPartyScreen_deviceEvents();
            findPartyScreen_windowEvents();
            findPartyScreen_elementsEvents();
        };

    // screen window events
    var findPartyScreen_windowEvents = function() {

            $('#findPartyScreen').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var findPartyScreen_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var findPartyScreen_elementsExtraJS = function() {
            // screen (findPartyScreen) extra code

            /* newPartyCollapseBlock */

            $("#findPartyScreen_newPartyCollapseBlock .ui-collapsible-heading-toggle").attr("tabindex", "7");

            /* partyCollapseBlock */

            $("#findPartyScreen_partyCollapseBlock .ui-collapsible-heading-toggle").attr("tabindex", "7");

        };

    // screen elements handler
    var findPartyScreen_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#findPartyScreen").on("pagebeforeshow", "#findPartyScreen", function(event, ui) {
        findPartyScreen_beforeshow();
    });

    if (runBeforeShow) {
        findPartyScreen_beforeshow();
    } else {
        findPartyScreen_onLoad();
    }
};

$(document).off("pagecreate", "#findPartyScreen").on("pagecreate", "#findPartyScreen", function(event, ui) {
    Appery.processSelectMenu($(this));
    findPartyScreen_js();
});